src/Entity/Candidat.php
<?php

namespace App\Entity;

use App\Repository\CandidatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CandidatRepository::class)
 */
class Candidat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="candidat", cascade={"persist", "remove"})
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cv;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $current_location;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nationality;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $availability;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $short_description;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $active;

    /**
     * @ORM\OneToMany(targetEntity=InfoAdminCandidat::class, mappedBy="candidat")
     */
    private $infoAdminCandidats;

    /**
     * @ORM\ManyToOne(targetEntity=JobCategory::class, inversedBy="Candidat")
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private $job_category;

    /**
     * @ORM\ManyToOne(targetEntity=Experience::class, inversedBy="candidat",cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")

     */
    private $experience;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $passport;

    /**
     * @ORM\ManyToOne(targetEntity=Gender::class, inversedBy="infoAdminCandidat")
     */
    private $gender;

    /**
     * @ORM\OneToMany(targetEntity=Candidature::class, mappedBy="candidat")
     */
    private $candidatures;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $birth_place;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birth_date;


    public function __construct()
    {
        $this->candidatures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCv(): ?string
    {
        return $this->cv;
    }

    public function setCv(string $cv): self
    {
        $this->cv = $cv;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getCurrentLocation(): ?string
    {
        return $this->current_location;
    }

    public function setCurrentLocation(string $current_location): self
    {
        $this->current_location = $current_location;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getAvailability(): ?bool
    {
        return $this->availability;
    }

    public function setAvailability(bool $availability): self
    {
        $this->availability = $availability;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getJobCategory(): ?JobCategory
    {
        return $this->job_category;
    }

    public function setJobCategory(?JobCategory $job_category): self
    {
        $this->job_category = $job_category;

        return $this;
    }

    public function getExperience(): ?Experience
    {
        return $this->experience;
    }

    public function setExperience(?Experience $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    public function getPassport(): ?string
    {
        return $this->passport;
    }

    public function setPassport(string $passport): self
    {
        $this->passport = $passport;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * @return Collection|Candidature[]
     */
    public function getCandidatures(): Collection
    {
        return $this->candidatures;
    }

    public function addCandidature(Candidature $candidature): self
    {
        if (!$this->candidatures->contains($candidature)) {
            $this->candidatures[] = $candidature;
            $candidature->setCandidat($this);
        }

        return $this;
    }

    public function removeCandidature(Candidature $candidature): self
    {
        if ($this->candidatures->removeElement($candidature)) {
            // set the owning side to null (unless already changed)
            if ($candidature->getCandidat() === $this) {
                $candidature->setCandidat(null);
            }
        }

        return $this;
    }

    public function getBirthPlace(): ?string
    {
        return $this->birth_place;
    }

    public function setBirthPlace(?string $birth_place): self
    {
        $this->birth_place = $birth_place;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(?\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function toArray(){
        return ['gender'=>$this->getGender(),
                'firstname'=>$this->getFirstName(), 
                'lastname'=>$this->getLastName(), 
                'adress' => $this->getAdress(), 
                'country' => $this->getCountry(),
                'nationality' => $this->getNationality(),
                'curriculumVitae' => $this->getCv(),
                'profilPicture' => $this->getProfilePicture(),
                'currentLocation' => $this->getCurrentLocation(),
                'dateOfBirth' => $this->getBirthDate(),
                'placeOfBirth' => $this->getBirthPlace(),
                'shortDescription' => $this->getShortDescription(),
                'experience' => $this->getExperience(),
                'jobCategory' => $this->getJobCategory(),
                'passportFile' => $this->getPassport()
            ];
    }

    public function profilIsCompleted()
    {
        return $this->getProfilCompletionPercent() === 100;
    }

    public function getProfilCompletionPercent()
    {
        $filledFieldCount = 0;
        $fields = $this -> toArray();

        foreach ($fields as $field){
            if (!empty($field)){
                $filledFieldCount ++ ;
            }
        }
       return $filledFieldCount * 100 / count($fields);
    }
}

src/Form/CandidatType.php
<?php

namespace App\Form;


use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use App\Entity\Experience;
use App\Entity\Candidat;
use App\Entity\Gender;
use App\Entity\JobCategory;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;



class CandidatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('first_name')
            ->add('last_name')

            ->add('country', TextType::class,[
                'required' => false,
                'empty_data' => '',
            ])

            ->add('cv', FileType::class, [
                'mapped'=>false,
                'required'=>false
            ])
            ->add('profile_picture', FileType::class, [
                'mapped'=>false,
                'required'=>false
            ])
            ->add('current_location', TextType::class,[
                'required' => false,
                'empty_data' => '',
            ])
            ->add('adress', TextType::class,[
                'required' => false,
                'empty_data' => '',
            ])
            ->add('nationality', TextType::class,[
                'required' => false,
                'empty_data' => '',
            ])
            ->add('availability')

            ->add('short_description', TextType::class,[
                'required' => false,
                'empty_data' => '',
            ])

            ->add('passport', FileType::class, [
                'mapped'=>false,
                'required'=>false
            ])

            ->add('job_category', EntityType::class, [
                'class'=>JobCategory::class
            ])

            ->add('experience', EntityType::class, [
                'class'=>Experience::class
            ])
            ->add('gender', EntityType::class, [
                'class'=>Gender::class
            ])
            ->add('birth_place')
            ->add('birth_date', DateType::class, [

                'widget'=>'single_text',

            ])
            
            ->add('user', UserType::class, [
                'mapped'=>false,
                'required'=>false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Candidat::class,
        ]);
    }
}

src/Controller/CandidatController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\File\Exception\FileException;
use App\Entity\Candidat;
use App\Form\CandidatType;
use App\Repository\CandidatRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints\Length;

/**
 * @Route("/")
 */
class CandidatController extends AbstractController
{
    /**
     * @Route("/admin/candidat", name="candidat_index", methods={"GET"})
     */
    public function index(CandidatRepository $candidatRepository): Response
    {
        return $this->render('candidat/index.html.twig', [
            'candidats' => $candidatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/admin/candidat/new", name="candidat_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $candidat = new Candidat();
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($candidat);
            $entityManager->flush();

            return $this->redirectToRoute('candidat_index');
        }

        return $this->render('candidat/new.html.twig', [
            'candidat' => $candidat,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/candidat/{id}", name="candidat_show", methods={"GET"})
     */
    public function show(Candidat $candidat): Response
    {
        return $this->render('candidat/show.html.twig', [
            'candidat' => $candidat,
        ]);
    }

    /**
     * @Route("/candidat/{id}/edit", name="candidat_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Candidat $candidat, SluggerInterface $slugger): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(CandidatType::class, $candidat);
        $form->handleRequest($request);
        $cv = $form->get('cv')->getData();
        $profile_picture = $form->get('profile_picture')->getData();
        $passport = $form->get('passport')->getData();

        

        if ($form->isSubmitted() && $form->isValid()) {

            if ($cv !== null) {
                $candidat->setCv($this->upload($cv, 'cv', $slugger));
            }
            if ($profile_picture !== null) {
                $candidat->setProfilePicture($this->upload($profile_picture, 'profile_picture', $slugger));
            }
            if ($passport !== null) {
                $candidat->setPassport($this->upload($passport, 'passport', $slugger));
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('candidat_edit',[
            'id'=> $candidat->getId(),

            ]);
        }

        return $this->render('candidat/edit.html.twig', [
            'candidat' => $candidat,
            'form' => $form->createView(),
            'user' => $user,
            'filledFieldCount'=> $candidat-> getProfilCompletionPercent(),
        ]);
    }

    /**
     * @Route("/candidat/{id}", name="candidat_delete", methods={"POST"})
     */
    public function delete(Request $request, Candidat $candidat): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidat->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($candidat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('candidat_index');
    }
    public function upload($file, $target_directory ,$slugger){
        if ($file) {
                    $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                    // this is needed to safely include the file name as part of the URL
                    $safeFilename = $slugger->slug($originalFilename);
                    $newFilename = $safeFilename.'-'.uniqid().'.'.$file->guessExtension();

                    // Move the file to the directory where brochures are stored
                    try {
                        $file->move(
                            $this->getParameter($target_directory),
                            $newFilename
                        );
                    } catch (FileException $e) {
                        // ... handle exception if something happens during file upload
                    }

                    // updates the 'brochureFilename' property to store the PDF file name
                    // instead of its contents
                    return $newFilename;
                }

        }
}

templates/candidat/_delete_form.html.twig
<form method="post" action="{{ path('candidat_delete', {'id': candidat.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidat.id) }}">
    <button class="btn">Delete</button>
</form>

templates/candidat/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Candidat{% endblock %}

{% block body %}


    <div class="base">

    <!-- Page -->
    <div class="page">

        <!-- Page Header-->
        <section class="page-title page-title-bg fixed-bg overlay dark-5 padding-top-160 padding-bottom-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2 class="white-text">Your profile</h2>
                        <span class="white-text">Personnal & Professionnal informations</span>
                        <ol class="breadcrumb">
                            <li><a href="#!">Home</a></li>
                            <li class="active">Profile</li>
                        </ol>
                    </div>
                </div>
            </div>
        </section>

        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}

        <!-- Page Content-->
        <section class="gray-bg">
            <div class="container">
                <div class="row">

                    <div class="score-container">
                            {% if filledFieldCount != 100 %}
                            
                                    <h4>
                                        &nbsp; Your profile is no completed.
                                    </h4>
                                {% else %}
                                    <h4>
                                        &nbsp; Hooray ! Your profile is complete.
                                    </h4>
                                {% endif %}
                                    

                                    <div class="c100 p{{filledFieldCount|round}} small complete ">
                                        <span>{{filledFieldCount|round}}%</span>
                                        <div class="slice">
                                            <div class="bar"></div>
                                            <div class="fill"></div>
                                        </div> 
                                    </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </section>

        
      {{ include('candidat/_form.html.twig') }}

    </div>

</div>
{% endblock %}

templates/candidat/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat index{% endblock %}

{% block body %}


   <h1 style="padding-bottom:2rem; padding-top:10rem; background-color: #2F3138;text-align: center; color:white;margin-top:0">Candidat list</h1>

    <table class="table" style="font-size:1rem;">
        <thead>
            <tr>
                <th>Profile_picture</th>
                <th>First_name</th>
                <th>Last_name</th>
                <th>Country</th>
                <th>Cv</th>
                <th>Current_location</th>
                <th>Adress</th>
                <th>Short_description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for candidat in candidats %}
            <tr>
                <td>
                {% if candidat.profilePicture is null %} 
                       <img style="width: 4rem; height: 5rem;"src="{{ asset ('uploads/picture/profiltype.jpg')}}">
                {% else %}
                <img style="width: 4rem; height: 4rem;" src="{{ asset ('uploads/picture/') ~ candidat.profilePicture }}">
                {% endif %}
                
                </td>
                <td>{{ candidat.firstName }}</td>
                <td>{{ candidat.lastName }}</td>
                <td>{{ candidat.country }}</td>
                <td><a href="{{ asset ('uploads/cv/') ~ candidat.cv }}"> 📂 </td>
                <td>{{ candidat.currentLocation }}</td>
                <td>{{ candidat.adress }}</td>
                <td>{{ candidat.shortDescription }}</td>
                <td>
                    <a style="width:7rem;height:3rem;font-size:0.8em;padding:initial;" href="{{ path('candidat_show', {'id': candidat.id}) }}"class="btn gradient grey lighten-2 black waves-effect waves-light btn-register">show</a>

                    <a style="width:7rem;height:3rem;font-size:0.8em;padding:initial;"href="{{ path('candidat_edit', {'id': candidat.id}) }}"class="btn gradient secondary  waves-effect waves-light btn-register">edit</a>
                </td>
            </tr>    
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('candidat_new') }}"class="btn bn-lg gradient grey lighten-2 black btn-block waves-effect waves-light btn-register">Create new</a>
        <a target="_self" href="{{ path ('admin_index')}}"class="btn bn-lg gradient secondary btn-block waves-effect waves-light btn-register"style="margin:0;">
    <span>Return to admin page</span></a>
{% endblock %}

templates/candidat/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Candidat{% endblock %}

{% block body %}
<h1 style="padding-bottom:2rem; padding-top:10rem; background-color: #2F3138;text-align: center; color:white;margin-top:0">Create new Candidat</h1>

    {{ include('candidat/_form.html.twig') }}

    <a href="{{ path('candidat_index') }}"class="btn bn-lg gradient secondary btn-block waves-effect waves-light btn-register; color:black;">back to list</a>
{% endblock %}

templates/candidat/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidat{% endblock %}

{% block body %}
   <h1 style="padding-bottom:2rem; padding-top:10rem; background-color: #2F3138;text-align: center; color:white;margin-top:0">Candidat details</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Profile_picture</th>
                                <td>
                {% if candidat.profilePicture is null %} 
                       <img style="width: 4rem; height: 5rem;"src="{{ asset ('uploads/picture/profiltype.jpg')}}">
                {% else %}
                <img style="width: 4rem; height: 4rem;" src="{{ asset ('uploads/picture/') ~ candidat.profilePicture }}">
                {% endif %}
                
                </td>
            </tr>

            <tr>
                <th>First_name</th>
                <td>{{ candidat.firstName }}</td>
            </tr>
            <tr>
                <th>Last_name</th>
                <td>{{ candidat.lastName }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ candidat.country }}</td>
            </tr>
            <tr>
                <th>Cv</th>
               <td><a href="{{ asset ('uploads/cv/') ~ candidat.cv }}"> See CV 🔎 </td>
            </tr>

            <tr>
                <th>Current_location</th>
                <td>{{ candidat.currentLocation }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ candidat.adress }}</td>
            </tr>
            <tr>
                <th>Nationality</th>
                <td>{{ candidat.nationality }}</td>
            </tr>
            <tr>
                <th>Availability</th>
                <td>{{ candidat.availability ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Short_description</th>
                <td>{{ candidat.shortDescription }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ candidat.active ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Passport</th>
                <td><a href="{{ asset ('uploads/passport/') ~ candidat.passport }}">  See passport🔎 </td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('candidat_index') }}">back to list</a>

    <a href="{{ path('candidat_edit', {'id': candidat.id}) }}">edit</a>

    {{ include('candidat/_delete_form.html.twig') }}
{% endblock %}